"""
Parcelle (Cadastral Parcel) Model.

Represents a cadastral parcel from the French Parcellaire Express dataset.
Data source: IGN Parcellaire Express (https://geoservices.ign.fr/parcellaire-express)
"""

from sqlalchemy import Column, Integer, String
from geoalchemy2 import Geometry

from database import Base


class Parcelle(Base):
    """
    SQLAlchemy model for cadastral parcels.
    
    Attributes:
        gid: Primary key (auto-generated by PostGIS import)
        idu: Identifiant Unique - unique parcel identifier
        numero: Parcel number within the section
        feuille: Sheet number
        section: Cadastral section identifier (e.g., "AB")
        code_dep: Department code (e.g., "02")
        nom_com: Commune name
        com_abs: Absorbed commune code
        code_arr: Arrondissement/prefix code
        contenance: Surface area in centiares (1 centiare = 0.01 m²)
        geom: Geometry (MultiPolygon in Lambert 93 / EPSG:2154)
    """
    
    __tablename__ = "parcelle"
    
    # Primary Key
    gid = Column(Integer, primary_key=True, index=True)
    
    # Parcel Identifiers
    idu = Column(String, index=True)          # Identifiant unique
    numero = Column(String)                    # Numéro de parcelle
    section = Column(String, index=True)       # Section cadastrale
    feuille = Column(Integer)                  # Numéro de feuille
    
    # Location Information
    code_dep = Column(String, index=True)      # Code département
    nom_com = Column(String)                   # Nom commune
    com_abs = Column(String)                   # Commune absorbée
    code_arr = Column(String)                  # Code arrondissement
    
    # Parcel Attributes
    contenance = Column(Integer)               # Surface en centiares
    
    # Geometry (Lambert 93)
    geom = Column(
        Geometry(
            geometry_type="MULTIPOLYGON",
            srid=2154,
            spatial_index=True
        )
    )
